version: '3'

services:
  smee-client:
    build:
      context: .
      dockerfile: Dockerfile.smee
    command: ["--target", "http://app:3000/api/webhook", "--url", "${SMEE_URL}"]
    environment:
      SMEE_URL: ${SMEE_URL}
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
       - ./:/usr/src/app/
